### ISSUE TITLE
Failed to initialize PSPDFKit: License too short

### ISSUE THREAD

**Issue by hmelenok** [PSPDFKit/pspdfkit-web-example-react#1]
License is seems correct but library won't load PDF 

![screen shot 2018-04-23 at 17 39 23](https://user-images.githubusercontent.com/2149114/39134314-09587e16-471f-11e8-8227-8839c3f3865d.png)

I used the same LICENCE key as for NPM to install lib but it says that it too short

**Comment by hmelenok** [comment]
Okay, not so obvious. Sorry for ticket, found another key at https://pspdfkit.com/guides/web/current/standalone/integration/#toc_integrate-as-a-module

**Comment by philipp-spiess** [comment]
@hmelenok Thanks for filing this issue. You're right, the license key is not the same as the npm bundle key. We'll make this clearer in the future.
