### ISSUE TITLE
Error at Incorrect response Mime type wasm

### ISSUE THREAD

**Issue by arnoldc** [PSPDFKit/pspdfkit-web-example-react#3]
Hi I tried all the steps that was mention in the guide for setting up `stand alone` guide
but im still caught up with this issue ,see below error in my chrome console 
 
> Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

did i miss anything?

**Comment by philipp-spiess** [comment]
Hi @arnoldc!

Unfortunalty the WebAssembly API requires the MIME type of `application/wasm` to enable advanced performance improvements but not all web servers support that yet: https://pspdfkit.com/guides/web/current/pspdfkit-for-web/troubleshooting/#response-has-unsupported-mime-type-error-cb6cf0

One workaround would be to use `yarn` to install the dependencies. With yarn, we can pin a transitive dependency to a specific version (in our case, we need `mime@1.6.0`, see [here](https://github.com/PSPDFKit/pspdfkit-web-example-react/blob/master/package.json#L44)).

**Comment by arnoldc** [comment]
ok thanks for letting me know, i will close this issue since it resolves my issue
thanks again
