### ISSUE TITLE
Locale Intl Error

### ISSUE THREAD

**Issue by Springbach** [PSPDFKit/pspdfkit-web-example-react#4]
Uncaught (in promise) Error: I18n: Cannot find translations for "en". Please retry or add them manually to PSPDFKit.I18n.messages["en"]
    at new r (pspdfkit.js?7c81:13)
    at eval (pspdfkit.js?7c81:13)
    at eval (pspdfkit.js?7c81:13)
    at tryCatch (runtime.js?96cf:62)
    at Generator.invoke [as _invoke] (runtime.js?96cf:296)
    at Generator.prototype.(:3000/anonymous function) [as throw] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at r (pspdfkit.js?7c81:13)
    at eval (pspdfkit.js?7c81:13)

**Comment by Springbach** [comment]
Didn't found this code at scripts/copy-pspdfkit-files.js

ncp(
  "./node_modules/pspdfkit/dist/pspdfkit-lib",
  "./public/pspdfkit-lib",
  err => {
    err && console.error(err);
  }
);

**Comment by philipp-spiess** [comment]
Hey @Springbach 

I'm glad you found a solution for the issue. When you run PSPDFKit for Web in Standalone mode it's important that you include our build artifacts as well.

We have more information in [our troubleshooting guides](https://pspdfkit.com/guides/web/current/pspdfkit-for-web/troubleshooting/?search=not%20find%20translations%20for%20%22en%22.#i18n-cannot-find-translations-for-en-please-retry-or-add-them-manually-to-pspdfkit-i18n-messages-en).

I'll also make sure that we have a more meaningful error message for this in the future!

Feel free to contact us on https://pspdfkit.com/support/request/ if you have more questions - This way we can respond even faster.
