### ISSUE TITLE
Error compiling 'nextProps' is not defined.

### ISSUE THREAD

**Issue by blak3r** [PSPDFKit/pspdfkit-web-example-react#5]
```
Failed to compile.

./src/components/pspdfkit/index.js
  Line 44:  'nextProps' is not defined  no-undef
```

I believe line 44 should be changed from:
```
      this.load(nextProps);
```
to
```
   this.load(this.props.pdfUrl)
```

**Comment by philipp-spiess** [comment]
Thanks @blak3r for catching this. I've fixed it in 67cbc67ba6ce9fb27ea3dc77b261e3ce8b24b914.

Feel free to contact us on https://pspdfkit.com/support/request/ if you have more questions - This way we can respond even faster.
